name: "Code Checking"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    name: "Linting - ESLint"
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip codechecking]') || contains(github.event.head_commit.message, '[skip codechecking eslint]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install NodeJS v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: |
          yarn --frozen-lockfile
      - name: Run ESLint
        uses: icrawl/action-eslint@v1

    editorconfig:
    name: "Formatting - EditorConfig"
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip codechecking]') || contains(github.event.head_commit.message, '[skip codechecking eclint]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install NodeJS v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Run EditorConfigLint
        run: npx eclint fix src scripts .github

  tsc:
    name: "Compiling - TSC"
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip codechecking]') || contains(github.event.head_commit.message, '[skip codechecking tsc]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install NodeJS v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: |
          yarn --frozen-lockfile
      - name: Copy Configuration
        run: |
          pushd src &&
          cp config.example.ts config.ts &&
          popd
      - name: Build Project
        uses: icrawl/action-tsc@v1
        with:
          build: src
