name: "Code Check"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip codecheck]') || contains(github.event.head_commit.message, '[skip codecheck eslint]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install NodeJS v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: |
          yarn --frozen-lockfile
      - name: Run ESLint
        uses: icrawl/action-eslint@v1

  tsc:
    name: TSC
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip codecheck]') || contains(github.event.head_commit.message, '[skip codecheck tsc]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install NodeJS v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: |
          yarn --frozen-lockfile
      - name: Copy Configuration
        run: |
          pushd src &&
          cp config.example.ts config.ts &&
          popd
      - name: Build Project
        uses: icrawl/action-tsc@v1
        with:
          build: src
